### ISSUE TITLE
qq音乐13.0版本没有魅族状态栏接口

### ISSUE THREAD

**Issue by qasg** [xiaowine/Lyrics-Getter#101]
从12.8版本过后qq音乐的状态栏歌词开关就没了，希望能修复一下

**Comment by xiaowine** [comment]
实测并没有问题，请重新优化后尝试

**Comment by qasg** [comment]
我重新优化过后依旧不行，我在MIUI14.0.7 安卓13上面最新版QQ音乐测试有状态栏接口，在k50 hyperos1.0.23 安卓14上没有魅族状态栏接口。

**Comment by qasg** [comment]
重新安装后有效果了，
