### ISSUE TITLE
请考虑下支持“歌词适配”，谢谢

### ISSUE THREAD

**Issue by mollyskat** [xiaowine/Lyrics-Getter#11]

**Comment by xiaowine** [comment]
歌词适配有播放功能？

**Comment by mollyskat** [comment]
有的，可以播放歌曲，类似洛雪音乐播放时也有歌词，酷安搜“歌词适配”可以找到该话题

**Comment by xiaowine** [comment]
> 有的，可以播放歌曲，类似洛雪音乐播放时也有歌词，酷安搜“歌词适配”可以找到该话题

我测试的时候只有下载音乐

**Comment by mollyskat** [comment]
点开搜索的歌会展开下载格式和播放，播放在最底下，播放后页面左下角有旋转的专辑图，再点开就显示歌词了，这个APP还能导入QQ音乐跟网易云账号下的歌单，如果Lyric-Getter考虑加上支持歌词适配，麻烦测试下这里能不能兼容，谢谢。
