### ISSUE TITLE
Apple Music1353（4.6.0）版本切换下一首歌曲不显示歌词

### ISSUE THREAD

**Issue by glxay** [xiaowine/Lyrics-Getter#112]
如题，并且需要手动打开Apple Music内歌词页面才能显示歌词
如何触发：
下载Apple Music1353版本
播放一首歌并等待它播完
下一首歌的歌词不会显示，需要手动打开歌词页面才会显示

**Comment by xiaowine** [comment]
因为并不在适配范围
