### ISSUE TITLE
Music cover displays improperly in Netease Music after using Lyric Getter

### ISSUE THREAD

**Issue by hrsthrt74** [xiaowine/Lyrics-Getter#118]
**Describe the bug**
Music cover displays improperly in Netease Music after using Lyric Getter. Triggered when using the new "Fullscreen Cover" player style and Lyric Getter. 

**To Reproduce**
1. Activate Lyric Getter checking Netease Music in LSPosed
2. Open Netease Music and go to Now Playing page
3. See error (the bottom of cover displays improperly)

**Expected behavior**
Following official behavior

**Screenshots**
Official Behavior
![Screenshot_2024-03-09-18-47-31-138_com netease cloudmusic](https://github.com/xiaowine/Lyric-Getter/assets/49299205/c0b29bcb-7c76-42b8-89a7-c023ec0578b6)
After using Lyrics Getter(look at the bottom of the cover)
![Screenshot_2024-03-09-18-46-25-874_com netease cloudmusic](https://github.com/xiaowine/Lyric-Getter/assets/49299205/1c1556c5-9fe3-4632-aa3c-04658419844b)

**Smartphone (please complete the following information):**
 - Device: Redmi K30 5G CN Ver.
 - OS: MIUI 13.0.3.0.SGICNXM, Android 12
 - Version: Netease Music: from 9.0.25 to 9.0.30, Lyric Getter 2.0.11

**Comment by xiaowine** [comment]
Turn on the second status bar lyrics switch in Netease Music settings

**Comment by hrsthrt74** [comment]
![Screenshot_2024-03-12-23-14-47-779_com netease cloudmusic](https://github.com/xiaowine/Lyric-Getter/assets/49299205/f5424eae-85bc-46c1-a442-17100b121a8b)
![Screenshot_2024-03-12-23-12-16-350_com netease cloudmusic](https://github.com/xiaowine/Lyric-Getter/assets/49299205/7ea64d0f-b488-4c4e-8d42-464d22f0dae8)
the problem remains🤔

**Comment by xiaowine** [comment]
I don't think it's the module's problem, it's NetEase Cloud Music's own problem

**Comment by hrsthrt74** [comment]
Problem resolved after updating Netease Music to 9.0.40🤔
Still wondering why
