### ISSUE TITLE
vanilla音乐0.2.0dev9（Google play最新版）提示api版本过低

### ISSUE THREAD

**Issue by IkiteruyoMite** [xiaowine/Lyrics-Getter#129]
![Screenshot_2024-04-13-23-15-06-952_cn lyric getter](https://github.com/xiaowine/Lyric-Getter/assets/166934885/4c29133b-57f9-4f4b-a996-106b8a077a98)

> 当前状态：过低的API版本
目前版本4，所需版本6

**Comment by 2315506431** [comment]
是vanilla的api版本低了，你应该去找vanilla的作者
