### ISSUE TITLE
請求適配BlackPlayer EX🙏

### ISSUE THREAD

**Issue by 0316ng** [xiaowine/Lyrics-Getter#143]
感謝您的指路

軟件名稱：BlackPlayer EX 
版本：20.62-407
很好用的一款本地播放器，可以讀取本地歌詞文件或歌曲內嵌歌詞，希望您能在閒暇之餘幫忙適配，不勝感激

附上應用截圖和安裝包

![Screenshot_2024-05-06-17-18-41-057_com kodarkooperativet blackplayerex](https://github.com/xiaowine/Lyric-Getter/assets/61930381/691462c6-bff1-445c-a83d-ea78be0d269a)

![IMG_20240507_170421](https://github.com/xiaowine/Lyric-Getter/assets/61930381/aba77049-4353-451e-92ab-afd5552a1108)

[BlackPlayer EX [20.62].zip](https://github.com/xiaowine/Lyric-Getter/files/15233249/BlackPlayer.EX.20.62.zip)

**Comment by xiaowine** [comment]
这个只能获取到现在播放的是啥，不能获取到歌词，暂时不考录

**Comment by 0316ng** [comment]
瞭解了😢，感謝🙏
