### ISSUE TITLE
请求适配拟声 🙏

### ISSUE THREAD

**Issue by Xr1ng** [xiaowine/Lyrics-Getter#146]
请求适配拟声

附上截图
![Screenshot_2024-05-13-00-09-55-100_com mimicry mymusic](https://github.com/xiaowine/Lyric-Getter/assets/61143353/a255964e-d769-48a4-ad85-12cb16c04b84)
附上下载地址
https://download.music.mimicry.cool/
🙏🙏

**Comment by xiaowine** [comment]
已适配
