### ISSUE TITLE
App规则改动

### ISSUE THREAD

**Issue by 2836995408** [xiaowine/Lyrics-Getter#153]
汽水音乐 9.7.0 未收录红米 K60Pro 可用但是有个 BUG 在汽水音乐主界面显示歌词会慢半拍，也就是在汽水音乐界面当中当状态栏歌词会显示上一句歌词一直慢一句，切到后台恢复正常

**Comment by 2836995408** [comment]
Uploading mmexport1717640650185.mp4…

**Comment by xiaowine** [comment]
预期
