### ISSUE TITLE
努比亚myos14.21不可用

### ISSUE THREAD

**Issue by Xtnayue** [xiaowine/Lyrics-Getter#155]
**努比亚myos14.21不可用**
试用椒盐音乐API6，及魅族状态栏模式
其中API6完全无反应
魅族状态栏模式双击可使状态栏图标消失，但歌词不显示

**复现方法**
按照官网教程操作

**截图**
![Screenshot_20240608_213220](https://github.com/xiaowine/Lyric-Getter/assets/77312757/fd642c1b-0675-4b3e-90c0-1cabb1500598)

**设备**
 - Device: Nubia Z60 Ultra  (NX721J)
 - OS: Android14
 - UI:MyOS14.0.21MR3

**Comment by xiaowine** [comment]
请提供状态栏歌词和歌词获取日志

**Comment by Xtnayue** [comment]
> 请提供状态栏歌词和歌词获取日志

- 状态栏歌词不显示，不显示歌词内容
- 请问怎样从debug版本获取日志
- 还有，我是不是应该在[StatusBarLyric](https://github.com/Block-Network/StatusBarLyric)发issue

**Comment by YouCanAi** [comment]
> > 请提供状态栏歌词和歌词获取日志
> 
> - 状态栏歌词不显示，不显示歌词内容
> - 请问怎样从debug版本获取日志
> - 还有，我是不是应该在[StatusBarLyric](https://github.com/Block-Network/StatusBarLyric)发issue

非也，如果您使用其他音乐软件能出来状态栏歌词那就说明状态栏歌词工作正常，如果没有请确保正确配置了状态栏歌词。

**Comment by xiaowine** [comment]
> > 请提供状态栏歌词和歌词获取日志
> 
> * 状态栏歌词不显示，不显示歌词内容
> * 请问怎样从debug版本获取日志
> * 还有，我是不是应该在[StatusBarLyric](https://github.com/Block-Network/StatusBarLyric)发issue

安装debug版本后就会在lsp里面显示日志，对应项目问题去对应项目
