### ISSUE TITLE
App 规则改动：Flamingo

### ISSUE THREAD

**Issue by Yos-X** [xiaowine/Lyrics-Getter#158]
Flamingo 已主动通过 API 适配 Lyric Getter 且可用。
能否再将规则加入 App 内？

### 预览
![screenshot](https://github.com/xiaowine/Lyric-Getter/assets/97019070/743fded9-599c-4723-bb1d-789fcee61d1f)

以及
[Flamingo 的频道](https://t.me/FlamingoUpdateAndNews)

**Comment by YouCanAi** [comment]
当然，如果您能确保可以正常工作可以自行进行pr添加该规则😇

**Comment by YouCanAi** [comment]
我注意到有一个[pr](https://github.com/xiaowine/Lyric-Getter/pull/159)已经将该规则更新，或许该issue可以关闭了
