### ISSUE TITLE
关于酷狗魅族状态栏歌词一些研究

### ISSUE THREAD

**Issue by ghhccghk** [xiaowine/Lyrics-Getter#160]
经过我测试魅族状态栏歌词从酷狗12开始支持能显示开关，但是不会输出歌词，貌似接口异常，调用方法为魅族默认hook方法，在最近版本会因为保护模式无法正常使用

**Comment by xiaowine** [comment]
请给定一个具体版本

**Comment by ghhccghk** [comment]
> 请给定一个具体版本

12.0.0

**Comment by ghhccghk** [comment]
` /* renamed from: a */
    public void m364345a(Intent intent) {
        if (intent.getBooleanExtra("is_from_status_bar_lyric", false)) {
            String stringExtra = intent.getStringExtra(LiveRoomGameEntity.KEY_TYPE_LYRIC);
            boolean booleanExtra = intent.getBooleanExtra("is_close", true);
            try {
                Class<?> cls = Class.forName("android.app.Notification");
                int intValue = ((Integer) C41254f.m245777a(cls, "FLAG_ALWAYS_SHOW_TICKER", (Object) null)).intValue();
                int intValue2 = ((Integer) C41254f.m245777a(cls, "FLAG_ONLY_UPDATE_TICKER", (Object) null)).intValue();
                Notification m364397n = m364397n();
                int i = m364397n.flags;
                Bundle bundle = Build.VERSION.SDK_INT >= 19 ? m364397n.extras : null;
                CharSequence charSequence = m364397n.tickerText;
                if (TextUtils.isEmpty(stringExtra)) {
                    stringExtra = null;
                }
                if (intValue <= 0) {
                    stringExtra = null;
                }
                m364397n.tickerText = stringExtra;
                m364397n.flags |= 32;
                if (intValue > 0 && !booleanExtra) {
                    if (Build.VERSION.SDK_INT >= 19) {
                        m364397n.extras.putBoolean("ticker_icon_switch", false);
                        m364397n.extras.putInt("ticker_icon", C40445R.drawable.ic_meizu_status_bar_lyric_logo);
                    }
                    m364397n.flags |= intValue;
                    m364397n.flags |= intValue2;
                } else {
                    m364397n.flags &= intValue ^ (-1);
                    m364397n.flags &= intValue2 ^ (-1);
                }
                try {
                    if (this.f352501c != null) {
                        m364344a(this.f352501c, m364397n);
                    } else {
                        m364343a(m364397n);
                    }
                } catch (Throwable th) {
                    C44103as.m267079e(th);
                    C41569b.m247961a().mo247966a(11305089, th);
                }
                m364397n.flags = i;
                if (Build.VERSION.SDK_INT >= 19) {
                    m364397n.extras = bundle;
                }
                m364397n.tickerText = charSequence;
            } catch (Exception e2) {
                C44103as.m267079e(e2);
                C41569b.m247961a().mo247966a(11305089, e2);
            }
        }
    }

`



这是我反编译的代码

**Comment by ghhccghk** [comment]
![Screenshot_20240612-221235](https://github.com/xiaowine/Lyric-Getter/assets/36808766/44d0c52c-f646-43ba-a164-dcf204b84510)

魅族状态栏hook 酷狗10.9.2有效果，但是没有显示通知渠道
蓝牙歌词在这版也能够工作
酷狗貌似针对魅族状态栏歌词可能还有bug，导致有些版本会进入保护模式

![image](https://github.com/xiaowine/Lyric-Getter/assets/36808766/e3a76ca4-df34-4270-831e-ea4b4dd5f8fa)
貌似可能是这个问题

**Comment by xiaowine** [comment]
12.0.0经过实际测试并没有问题

**Comment by ghhccghk** [comment]
> 12.0.0经过实际测试并没有问题

我这边主要是想把api接口从车载切换到魅族状态栏这样的，车载肯定没问题，我自己慢慢研究吧，我先关闭这个comment了

**Comment by ghhccghk** [comment]
![Screenshot_20240720-012405_酷狗音乐](https://github.com/user-attachments/assets/9b5ecb35-3ed0-4e22-a374-ea52159fcf60)

目前在第三方内建状态栏歌词的系统测试成功hook ，最低版本如图所示
因为在最新版本下hook这两段会崩溃
所以我这个debug版本没有hook，但是使用墨状态栏歌词时候必须hook，不然没有办法生成这个开关，然后酷狗必须使用本地广播的方式来获取状态栏歌词，所以得要想办法实现从本地广播获取歌词


有问题hook代码

Class::class.java.methodFinder().first { name == "getField" }.replaceName()

            Class::class.java.methodFinder().first { name == "getDeclaredField" }.replaceName()
            return this

**Comment by ghhccghk** [comment]
![Screenshot_20240720-014838_Alpha Launcher](https://github.com/user-attachments/assets/6f33c6e8-d9f3-4ec4-b751-858a50e629ef)

![Screenshot_20240720-014509_酷狗音乐](https://github.com/user-attachments/assets/d81882e1-6b98-4555-bea8-8cf3dd3ff431)

![Screenshot_20240720-014756_Alpha Launcher](https://github.com/user-attachments/assets/fffa96cc-edb4-4585-856f-e016e0fad7b2)


给个完整图，说明我不是通过车载歌词处获取
