### ISSUE TITLE
网易云音乐hook后会丢失平板UI的适配

### ISSUE THREAD

**Issue by ybhgl** [xiaowine/Lyrics-Getter#165]
网易云音乐9.1.0版本对小米和OPPO平板进行了界面UI适配，经测试hook后会使界面变回手机版UI，去掉hook后恢复平板UI

**Comment by ghhccghk** [comment]
那是因为改成了魅族机型，不然无法获取状态栏歌词

**Comment by xiaowine** [comment]
> 那是因为改成了魅族机型，不然无法获取状态栏歌词

并不会对系统界面改机型，请查看代码后再发言

**Comment by ghhccghk** [comment]
> > 那是因为改成了魅族机型，不然无法获取状态栏歌词
> 
> 并不会对系统界面改机型，请查看代码后再发言

我说网易云界面ui适配可能靠机型识别，代码里对网易云 hook修改了机型

**Comment by xiaowine** [comment]
> > 那是因为改成了魅族机型，不然无法获取状态栏歌词
> 
> 并不会对系统界面改机型，请查看代码后再发言

我误解你你的意思，我道歉
