### ISSUE TITLE
有没有方法满足灵动岛上使用

### ISSUE THREAD

**Issue by langkiss** [xiaowine/Lyrics-Getter#172]
目前只会搭配状态栏歌词，因为hook需要占用时钟而模块实现的灵动岛还有空地，只要让获取的歌词被判断为通知就可以，大佬们有没有思路可以实现？

**Comment by VictorModi** [comment]
据我所知 灵动岛 是 iPhone 上才拥有的功能。

或者说你指的是 HyperOS 的 灵动提示？

以及任何形式的显示歌词都不是 Lyric Getter 应该做的，它只是一个歌词行提供器。
