### ISSUE TITLE
希望能适配Musicolet

### ISSUE THREAD

**Issue by Oneton429** [xiaowine/Lyrics-Getter#18]
**Is your feature request related to a problem? Please describe.**
当本模块的作用范围包括Musicolet时，Musicole打开即闪退。(墨状态栏歌词的作用范围包括Musicolet时，同样也会闪退。)

**Describe the solution you'd like**
希望支持Musicolet。

**Describe alternatives you've considered**
Musicolet为本地音乐播放器，通过读取歌曲的内嵌信息和lrc文件来获取歌词。也许可以通过读取歌曲文件或lrc文件来实现？

**Additional context**
无。

**Comment by xiaowine** [comment]
有没有可能闪退是因为他检测hook

**Comment by Oneton429** [comment]
啊 似乎真的是
那怎么办呢  （不过去掉hook检测的办法应该有的吧 要不QQ微信那些模块早就不能用了趴）
要不就用一些免root状态栏歌词的方法 读通知+读文件实现？就是延迟会高一些

**Comment by xiaowine** [comment]
> 啊 似乎真的是
> 那怎么办呢  （不过去掉hook检测的办法应该有的吧 要不QQ微信那些模块早就不能用了趴）
> 要不就用一些免root状态栏歌词的方法 读通知+读文件实现？就是延迟会高一些

微信qq不检测

**Comment by Oneton429** [comment]
> 有没有可能闪退是因为他检测hook

今日发现，墨状态栏歌词(6.0.2)和lyrics getter(2.0.5)作用域包括Musicolet(6.10.1 build454)时不再闪退
故重新请求适配
