### ISSUE TITLE
请求适配 Gramophone

### ISSUE THREAD

**Issue by Paspartame** [xiaowine/Lyrics-Getter#182]
项目地址 https://github.com/AkaneTan/Gramophone

**Comment by ghhccghk** [comment]
支持得改软件源代码，目前已经成功调试
![Screenshot_20241022-223955](https://github.com/user-attachments/assets/c3cf60f9-0c74-4bd6-9f64-563d570afcdc)
![Screenshot_20241022-224049](https://github.com/user-attachments/assets/bd6c3dbd-9c19-4537-86c8-c6c7482a97ad)

**Comment by Paspartame** [comment]
感谢感谢！期待CI版本😋

**Comment by ghhccghk** [comment]
![Screenshot_20241023-182421](https://github.com/user-attachments/assets/d6d362f7-0e02-4fa7-85ab-14f7d1284562)
调试差不多了，优化一下代码

**Comment by ghhccghk** [comment]
https://github.com/xiaowine/Lyric-Getter/pull/225 等把
