### ISSUE TITLE
App规则改动

### ISSUE THREAD

**Issue by sayainchina** [xiaowine/Lyrics-Getter#19]
**您的功能请求是否与问题有关？请描述。
是的，我的请求与问题有关，核心是关于酷狗11.7.0无法获取歌词

** 请简明扼要地描述问题所在。
当我使用酷狗11.7.0的时候，无法获取歌词，我降级到11.6.8的时候可以正常获取歌词

**描述您想要的解决方案**
酷狗11.7.0无法获取歌词

**描述您考虑过的替代方案*** 
告诉用户们，需要降级至11.6.8使用或者对规则进行更新

**补充背景***
红米K30 pro 安卓12 模块版本2.0.0 模块版本号 8 release 版 API 5

**Comment by xiaowine** [comment]
11.7.0正常获取歌词
