### ISSUE TITLE
求适配QQ音乐9.7.0.4版本

### ISSUE THREAD

**Issue by CityHunter-555** [xiaowine/Lyrics-Getter#196]
如题，因为QQ音乐9.7.0.4版本有魔法色和dts等优势，还有一部分潜在用户需要适配

**Comment by xiaowine** [comment]
> 如题，因为QQ音乐9.7.0.4版本有魔法色和dts等优势，还有一部分潜在用户需要适配

是否有魅族状态栏歌词，没有那么并不好适配，如果有，那么大概率也是支持的
