### ISSUE TITLE
Add Support for Stellio Player

### ISSUE THREAD

**Issue by bigjackwww** [xiaowine/Lyrics-Getter#199]
Problem: Lyric-Getter lacks support for Stellio Player, making it difficult to fetch lyrics while using Stellio.

Solution: Integrate Stellio Player support within Lyric-Getter to automatically retrieve and display lyrics for songs played in Stellio.

Alternatives: Manual lyric searches or using third-party apps to link Stellio with Lyric-Getter, but these are less convenient.

Additional Context: Stellio Player's customization and audio features make it a popular choice, and adding support in Lyric-Getter would enhance user experience

**Comment by xiaowine** [comment]
It doesn't support my phone, and I can't adapt until I change my phone to support him or it supports my phone
