### ISSUE TITLE
哔哩哔哩视频标题会被当作歌词获取

### ISSUE THREAD

**Issue by ghost** [xiaowine/Lyrics-Getter#200]
哔哩哔哩的视频标题会被当作歌词获取。

在哔哩哔哩中打开任意视频，返回桌面然后再回到哔哩哔哩，视频标题会被当作歌词被获取，然后显示在状态栏上。

然而它并不应该被当做歌词被获取

https://github.com/user-attachments/assets/138ddb36-d459-42d1-84e9-98a561ee7663

![IMG_20241002_112803](https://github.com/user-attachments/assets/8bb726de-ffb6-4f53-b8a3-f677d41233e4)
![IMG_20241002_112824](https://github.com/user-attachments/assets/dff1e4c1-7d9d-462d-ba20-f0dc5e587d11)

使用了[墨•状态栏歌词](https://github.com/Block-Network/StatusBarLyric/releases)
版本：2.0.14
设备：Redmi Note 12 Turbo
系统：HyperOS 1.0.6.0
XP框架：[LSPosed 1.9.3_mod](https://github.com/mywalkb/LSPosed_mod/releases)（是修改版）

**Comment by sherkent** [comment]
这是你的设置问题，检查你的设置
