### ISSUE TITLE
为多个模块/音乐同时使用添加支持

### ISSUE THREAD

**Issue by sherkent** [xiaowine/Lyrics-Getter#202]
当我同时使用息屏显示歌词和状态栏歌词的模块时，发现只有其中一个（息屏显示歌词）可以正常显示歌词，另一个则不起作用

我希望可以同时让两个模块/软件都能正常显示歌词（在同时开启使用的时候）

**Comment by xiaowine** [comment]
正常是都可以使用的

**Comment by sherkent** [comment]
> 正常是都可以使用的

**Comment by sherkent** [comment]
我必须将息屏歌词模块关闭，重启作用域，然后再打开，再重启作用域才能正常使用，不知道问题出在哪> 正常是都可以使用的
