### ISSUE TITLE
洛雪最新版本无法显示状态栏歌词 

### ISSUE THREAD

**Issue by xiaobaibukeaiya** [xiaowine/Lyrics-Getter#203]
lg版本2.0.14，洛雪音乐版本号1.6.0 打开了桌面，显示不出来状态栏歌词

**Comment by xiaobaibukeaiya** [comment]
但是有一个修改版的LG版本又可以获取洛雪音乐的歌词

**Comment by xiaowine** [comment]
经过测试，2.0.14能正常获取歌词

**Comment by xiaobaibukeaiya** [comment]
> 经过测试，2.0.14能正常获取歌词

可能是lsp框架的问题吗？我用的是lsp-mod 用的是状态栏歌词的模块也就是修改版的系统界面

**Comment by xiaowine** [comment]
> > 经过测试，2.0.14能正常获取歌词
> 
> 可能是lsp框架的问题吗？我用的是lsp-mod 用的是状态栏歌词的模块也就是修改版的系统界面

自行排查，都有可能

**Comment by xiaobaibukeaiya** [comment]
> > > 经过测试，2.0.14能正常获取歌词
> > 
> > 可能是lsp框架的问题吗？我用的是lsp-mod 用的是状态栏歌词的模块也就是修改版的系统界面
> 
> 自行排查，都有可能

好的，谢谢

**Comment by nymanyim** [comment]
@xiaowine 
洛雪最新版1.7.0失效，请求适配。

**Comment by xiaobaibukeaiya** [comment]
> @xiaowine 
> 洛雪最新版1.7.0失效，请求适配。

我这是正常的啊
