### ISSUE TITLE
能不能适配一下华为音乐？

### ISSUE THREAD

**Issue by Yanhualailou** [xiaowine/Lyrics-Getter#204]
emmm华为音乐版权很多很多，所以我一直在用这个软件，且咱们的模块好像也支持其他的系统音乐（荣耀和魅族），不知道有没有机会适配一下？

**Comment by ghhccghk** [comment]
![image](https://github.com/user-attachments/assets/fc5ffc3d-aae2-47c4-b624-ca091527d933)
成功hook，等我调试完成即合并

**Comment by ghhccghk** [comment]
![image](https://github.com/user-attachments/assets/d199e6fc-0137-4c0d-81bf-7caef3b06962)
完事

**Comment by ghhccghk** [comment]
测试结果目前得戴耳机服了

**Comment by xiaowine** [comment]
> 测试结果目前得戴耳机服了

可以尝试下hook蓝牙判断
https://github.com/xiaowine/Lyric-Getter/blob/master/app/src/main/kotlin/cn/lyric/getter/tool/HookTools.kt#L73

**Comment by ghhccghk** [comment]
> > 测试结果目前得戴耳机服了
> 
> 可以尝试下hook蓝牙判断 https://github.com/xiaowine/Lyric-Getter/blob/master/app/src/main/kotlin/cn/lyric/getter/tool/HookTools.kt#L73

没有用准备找别的hook点

**Comment by ghhccghk** [comment]
好难找函数

**Comment by ghhccghk** [comment]
![image](https://github.com/user-attachments/assets/e879372a-d4a1-4b26-a4e0-2efc370e10e5)
完事

**Comment by Yanhualailou** [comment]
那什么时候能用呢，目前模块还是不支持华为音乐😘

**Comment by ghhccghk** [comment]
> 那什么时候能用呢，目前模块还是不支持华为音乐😘

https://github.com/xiaowine/Lyric-Getter/actions
去这里下测试版
