### ISSUE TITLE
酷狗音乐hook 歌词会发送两次会，导致歌词动画多一次

### ISSUE THREAD

**Issue by ghhccghk** [xiaowine/Lyrics-Getter#206]
![image](https://github.com/user-attachments/assets/cce09689-4e6e-4bca-809b-edbc42aacf61)
.
我不会修，所以先报bug了

**Comment by xiaowine** [comment]
> ![image](https://private-user-images.githubusercontent.com/36808766/373945863-cce09689-4e6e-4bca-809b-edbc42aacf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTczNTAsIm5iZiI6MTcyODIxNzA1MCwicGF0aCI6Ii8zNjgwODc2Ni8zNzM5NDU4NjMtY2NlMDk2ODktNGU2ZS00YmNhLTgwOWItZWRiYzQyYWFjZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEyMTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZmM3ZTljNjQ5ZTNiOTI1ZWQyZTBlZmI4ZTc0ZTVmNDRiNTQ5ZTY3ZWE4NDk0M2EyNDAwNDA0MGViMWRkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZIYNY68rwOraYSQkmH6n03v4Ij9iCjEBEdtwBF2cMl8) . 我不会修，所以先报bug了

直接加一个属性，赋值歌词，下一句判断是不是一样的吧，这样最简单

**Comment by ghhccghk** [comment]
> > ![image](https://private-user-images.githubusercontent.com/36808766/373945863-cce09689-4e6e-4bca-809b-edbc42aacf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTczNTAsIm5iZiI6MTcyODIxNzA1MCwicGF0aCI6Ii8zNjgwODc2Ni8zNzM5NDU4NjMtY2NlMDk2ODktNGU2ZS00YmNhLTgwOWItZWRiYzQyYWFjZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEyMTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZmM3ZTljNjQ5ZTNiOTI1ZWQyZTBlZmI4ZTc0ZTVmNDRiNTQ5ZTY3ZWE4NDk0M2EyNDAwNDA0MGViMWRkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZIYNY68rwOraYSQkmH6n03v4Ij9iCjEBEdtwBF2cMl8) . 我不会修，所以先报bug了
> 
> 直接加一个属性，赋值歌词，下一句判断是不是一样的吧，这样最简单

不行，是两个进程，不能呢

**Comment by xiaowine** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/36808766/373945863-cce09689-4e6e-4bca-809b-edbc42aacf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTczNTAsIm5iZiI6MTcyODIxNzA1MCwicGF0aCI6Ii8zNjgwODc2Ni8zNzM5NDU4NjMtY2NlMDk2ODktNGU2ZS00YmNhLTgwOWItZWRiYzQyYWFjZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEyMTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxZmM3ZTljNjQ5ZTNiOTI1ZWQyZTBlZmI4ZTc0ZTVmNDRiNTQ5ZTY3ZWE4NDk0M2EyNDAwNDA0MGViMWRkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZIYNY68rwOraYSQkmH6n03v4Ij9iCjEBEdtwBF2cMl8) . 我不会修，所以先报bug了
> > 
> > 
> > 直接加一个属性，赋值歌词，下一句判断是不是一样的吧，这样最简单
> 
> 不行，是两个进程，不能呢

我在hook阶段过滤掉了一个进程
https://github.com/xiaowine/Lyric-Getter/commit/13cf485e3574c2dffeffd0f4e9a00ac316cf72bb
