### ISSUE TITLE
请求适配一下青盐云听，

### ISSUE THREAD

**Issue by AITNR** [xiaowine/Lyrics-Getter#21]
请求适配一下青盐云听，
和椒盐音乐是同一开发者
包名是com.xuncorp.qinalt.music
青盐云听提供了api5
![Screenshot_2023-08-12-08-11-32-268_com xuncorp qinalt music](https://github.com/xiaowine/Lyric-Getter/assets/86136733/6bc3e70d-d98e-4d32-b541-d6808fc69c71)

**Comment by xiaowine** [comment]
你把他添加到作用域就行了

**Comment by AITNR** [comment]
> 你把他添加到作用域就行了

加入了但还是不行

**Comment by xiaowine** [comment]
> > 你把他添加到作用域就行了
> 
> 加入了但还是不行

来个apk

**Comment by AITNR** [comment]
> > > 你把他添加到作用域就行了
> > 
> > 加入了但还是不行
> 
> 来个apk

https://www.123pan.com/s/XtNiVv-DqECd.html

**Comment by xiaowine** [comment]
> > > > 你把他添加到作用域就行了
> > > 
> > > 
> > > 加入了但还是不行
> > 
> > 
> > 来个apk
> 
> https://www.123pan.com/s/XtNiVv-DqECd.html

他加了api，但是又360加固了，所以不行
