### ISSUE TITLE
添加功能

### ISSUE THREAD

**Issue by sherkent** [xiaowine/Lyrics-Getter#219]
能屏蔽某个应用，使其无法从lyric-getter获取歌词吗

**Comment by xiaowine** [comment]
无法做到，因为歌词是通过广播传输，整个系统都可以获取

**Comment by sherkent** [comment]
> 无法做到，因为歌词是通过广播传输，整个系统都可以获取

那能否为强制显示歌词功能添加应用黑/白名单呢？
