### ISSUE TITLE
酷狗音乐概念版无法获取歌词

### ISSUE THREAD

**Issue by lixt0** [xiaowine/Lyrics-Getter#230]
酷狗音乐概念版无法获取歌词
 
环境：
LSPosed1.10.0(7068)
酷狗音乐概念版版本3.5.2
![IMG_20241103_115831](https://github.com/user-attachments/assets/e4c7e029-fcff-4396-9cb4-09cae80647b2)

**Comment by xiaowine** [comment]
已经修复，未发版
