### ISSUE TITLE
酷狗音乐魅族状态栏歌词hook失败

### ISSUE THREAD

**Issue by chennanye** [xiaowine/Lyrics-Getter#235]
2.0.14版本可以hook成功，但是最新版本hook就失败了，酷狗音乐版本为官方最新版
![Screenshot_2024-11-10-00-33-52-380_cn lyric getter](https://github.com/user-attachments/assets/2945146a-5688-4230-a34e-4889ec1b8833)

**Comment by xiaowine** [comment]
重复 #230

**Comment by chennanye** [comment]
> 重复 #230
我的能获取歌词，是这个开关在新版本没有
![Screenshot_2024-11-10-01-49-37-555_com kugou android](https://github.com/user-attachments/assets/ffb625b5-e133-458e-848d-11dba581f4d2)
![Screenshot_2024-11-10-01-49-21-981_cn lyric getter](https://github.com/user-attachments/assets/1fe6d01a-953e-42b7-b3b4-d3b2e514a5d7)
![Screenshot_2024-11-10-01-48-26-833_com kugou android](https://github.com/user-attachments/assets/4fc427fe-0648-41cb-afad-cd88a53e0f47)
