### ISSUE TITLE
可以适配一下音乐播放器吗？

### ISSUE THREAD

**Issue by j52011** [xiaowine/Lyrics-Getter#236]
包名是music.hifistatus

**Comment by j52011** [comment]
[](url)

**Comment by j52011** [comment]
![Uploading Screenshot_2024-11-10-21-16-25-929_yos.music.player.jpg…]()

**Comment by ghhccghk** [comment]
应用在哪里下载的，给个链接，最好是国内外上架应用商店的，看看ok不

**Comment by j52011** [comment]
> 应用在哪里下载的，给个链接，最好是国内外上架应用商店的，看看ok不

我自己加入包名解决了

**Comment by j52011** [comment]
我自己加入包名解决了
