### ISSUE TITLE
酷狗音乐无法打开状态栏歌词

### ISSUE THREAD

**Issue by VAabcjjsw** [xiaowine/Lyrics-Getter#253]
酷狗音乐最新版本20.0.0无法使用魅族状态栏歌词（小米商店下载的官方版），没有这个开关。并且车载蓝牙也不好使。已经确认模块可以正常使用，因为网易云音乐可以正常使用

**Comment by xiaowine** [comment]
测试版已修复

**Comment by VAabcjjsw** [comment]
> 测试版已修复

想问一下在哪里下载测试版呢？

**Comment by xiaowine** [comment]
https://github.com/xiaowine/Lyric-Getter/actions/workflows/android.yml
找第一个成功的点进去就能下载

**Comment by VAabcjjsw** [comment]
> https://github.com/xiaowine/Lyric-Getter/actions/workflows/android.yml 找第一个成功的点进去就能下载

已经解决，感谢大佬！那我close了
