### ISSUE TITLE
希望能加一个自定义功能，有些软件不方便

### ISSUE THREAD

**Issue by zhongwen-4** [xiaowine/Lyrics-Getter#27]
那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？

**Comment by xiaowine** [comment]
> 那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？

那么你是想要什么自定义功能

**Comment by zhongwen-4** [comment]
> > 那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？
> 
> 那么你是想要什么自定义功能

就是规则自定义()

**Comment by xiaowine** [comment]
> > > 那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？
> > 
> > 
> > 那么你是想要什么自定义功能
> 
> 就是规则自定义()

规则只是用来看的

**Comment by zhongwen-4** [comment]
> > > > 那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？
> > > 
> > > 
> > > 那么你是想要什么自定义功能
> > 
> > 
> > 就是规则自定义()
> 
> 规则只是用来看的

啊，那为什么lx music二改版不支持(

**Comment by xiaowine** [comment]
> > > > > 那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？
> > > > 
> > > > 
> > > > 那么你是想要什么自定义功能
> > > 
> > > 
> > > 就是规则自定义()
> > 
> > 
> > 规则只是用来看的
> 
> 啊，那为什么lx music二改版不支持(

问二改的

**Comment by zhongwen-4** [comment]
> > > > > > 那个，希望能加个自定义功能，因为有些软件不方便发出来，作者大大也不用那么麻烦不是？
> > > > > 
> > > > > 
> > > > > 那么你是想要什么自定义功能
> > > > 
> > > > 
> > > > 就是规则自定义()
> > > 
> > > 
> > > 规则只是用来看的
> > 
> > 
> > 啊，那为什么lx music二改版不支持(
> 
> 问二改的

那没事了，我一直以为是状态栏歌词这模块还是什么东西有问题()
