### ISSUE TITLE
多行歌词只显示第一行怎么办？可否自定义？

### ISSUE THREAD

**Issue by Otakukisaragishintaro** [xiaowine/Lyrics-Getter#42]
例如第一行是日语第二行是中文这种，我想看中文怎么办？

**Comment by xiaowine** [comment]
目前所有方法获取到的歌词，只有原文

**Comment by Otakukisaragishintaro** [comment]
是否可以hook之类的方法截取网易云自带的桌面歌词或者状态栏歌词的手段得到翻译呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月15日(周五) 晚上11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xiaowine/Lyric-Getter] 多行歌词只显示第一行怎么办？可否自定义？ (Issue #42)




 
目前所有方法获取到的歌词，只有原文
