### ISSUE TITLE
洛雪音乐（6.0.2）无法使用2.0以上的版本

### ISSUE THREAD

**Issue by lyricsb** [xiaowine/Lyrics-Getter#57]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaowine** [comment]
提供一个apk

**Comment by lyricsb** [comment]
https://github.com/lyswhut/lx-music-mobile#readme

**Comment by lyricsb** [comment]
标题有误，最新洛雪音乐为1.1.1版本

**Comment by xiaowine** [comment]
已修复
