### ISSUE TITLE
请求适配

### ISSUE THREAD

**Issue by 3269989121** [xiaowine/Lyrics-Getter#58]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 3269989121** [comment]
Redmi Note 11T Pro+ MIUI13.0.14反复经过教程无法使用，所有根权限已使用，用到的软件小米音乐（4.5.1.3），网易云音乐（7.3.3.0）都无效果，请官方坐下适配谢谢

**Comment by xiaowine** [comment]
下次能不能内容和标题一起写，别分开发
还有你这个标题也不对呀，帮你改了
最后提供下apk
