### ISSUE TITLE
新增关于重启系统界面功能

### ISSUE THREAD

**Issue by OldDream666** [xiaowine/Lyrics-Getter#80]
因为MIUI或hyperOS系统特性，切换和深浅色模式后需要重启系统页面，手动重启很是繁琐，用户大部分听歌时间也是晚上。
所以，能否开发一个自动重启系统页面的选项，可以让用户定时，自动重启。或者获取到系统当前切换了深浅色模式状态时自动重启（既然有提示弹出我认为是可以获取到这个状态的）。

希望作者大大能尝试设计一下！期望在下一版本遇见！

**Comment by xiaowine** [comment]
1.这个问题已经修复，更新状态栏歌词模块
2.主页右下角的图标就是重启

**Comment by OldDream666** [comment]
奇怪我刚刚更新，但是依旧有提示，功能依旧不正常

**Comment by xiaowine** [comment]
> 奇怪我刚刚更新，但是依旧有提示，功能依旧不正常

再试试？

**Comment by OldDream666** [comment]
重新获取hook点之后成功了，没有提示了，切换也有歌词了。谢谢作者！
可以close了

**Comment by OldDream666** [comment]
已解决
