### ISSUE TITLE
一直显示未激活

### ISSUE THREAD

**Issue by wrz-wrs** [xiaowine/Lyrics-Getter#88]
**软件一直显示未激活**
1. 点击重启了软件红色按钮重启软件无效
2. 重启手机也无效
3. 检查软件管理权限无异常

**Screenshots**

![微信图片_20231127172346](https://github.com/xiaowine/Lyric-Getter/assets/17489972/35dea7bb-7eea-438d-b101-8e755e444581)

**Comment by xiaowine** [comment]
lsp关闭激活后重新打开

**Comment by wrz-wrs** [comment]
关闭激活？没有找到怎么关闭激活呢，只有一个重启软件的
