### ISSUE TITLE
请求适配APPLE MUSIC 1330或增加hook点测试

### ISSUE THREAD

**Issue by Seeger0216** [xiaowine/Lyrics-Getter#90]
**Is your feature request related to a problem? Please describe.**
apple music目前是适配到了1299，能否继续适配新版？如果工作量较大，能否在lyrics-getter里面添加类似于墨状态栏的hook点测试功能？这样可以减少实际能hook但版本不在范围内而无法使用的问题

**Comment by xiaowine** [comment]
重复iss，我先关了 #87
