### ISSUE TITLE
Apple Music可支持1330版本，建议修改不支持字条

### ISSUE THREAD

**Issue by battenmufang** [xiaowine/Lyrics-Getter#91]
1330版本下可支持，但是切歌时需要手动回到APP内获取歌词，否则不继续显示。
附图表示可以使用
![Screenshot_2023-11-29-23-58-30-878_cn lyric getter](https://github.com/xiaowine/Lyric-Getter/assets/67583271/230026fb-ed3d-4620-8e34-79a34abdb6ed)

**Comment by xiaowine** [comment]
这种同样属于不支持
