### ISSUE TITLE
[bug] Android 13 上 systemui 清除歌词 hook 失效

### ISSUE THREAD

**Issue by duzhaokun123** [xiaowine/Lyrics-Getter#94]
**Describe the bug**
这个 Android 13 的 systemui 的`NotificationMediaManager`没有`clearCurrentMediaNotification`

好像被内联了(?)

**To Reproduce**
反编译 systemui 和官方源码对比

**Expected behavior**
有`clearCurrentMediaNotification`

**Screenshots**
<img width="928" alt="image" src="https://github.com/xiaowine/Lyric-Getter/assets/39830683/3d28c0f6-6765-4c68-a439-40adf5556fb8">
<img width="1280" alt="image" src="https://github.com/xiaowine/Lyric-Getter/assets/39830683/0fa12eb9-02b4-45ba-a056-3cc71a5481d5">

**Smartphone (please complete the following information):**
 - Device: OnePlus9
 - OS: Nameless Aosp
 - Version: 13

**Additional context**
系统界面_13.apk (github 抱怨文件太大)
https://1drv.ms/u/s!AmzlthxZuudNhgattru73vPQXREu?e=ETM4ib

**Comment by duzhaokun123** [comment]
测试按 api >= 34 的方法处理就正常了

**Comment by xiaowine** [comment]
有这个方法的，可能是一加魔改了
![image](https://github.com/xiaowine/Lyric-Getter/assets/68009112/4a561716-c7a9-4f6a-aed9-5fcf8b76a947)

**Comment by duzhaokun123** [comment]
> 有这个方法的，可能是一加魔改了

然而我甚至用的不是一加官方 rom
