### ISSUE TITLE
网易云音乐不显示状态栏歌词

### ISSUE THREAD

**Issue by Friendlydz** [xiaowine/Lyrics-Getter#95]
网易云音乐不显示状态栏歌词，QQ音乐和小米音乐能正常显示，没有装其他状态栏模块，网易云音乐设置中也未发现冲突的设置。
网易云音乐截图中的状态栏歌词是网易云音乐自带的，开启之后不是墨状态栏歌词。
手机是小米13，系统版本MIUI14.0.31，Android13。
望大佬解决。
![Screenshot_2023-12-13-11-44-06-463_com netease cloudmusic](https://github.com/xiaowine/Lyric-Getter/assets/122248140/4ecf4764-7cc4-4751-9a62-23e028c359d7)

![Screenshot_2023-12-13-11-39-28-105_com netease cloudmusic](https://github.com/xiaowine/Lyric-Getter/assets/122248140/b486136f-e1dd-4a63-bee1-812dfd785124)
![Screenshot_2023-12-13-11-39-49-669_com tencent qqmusic](https://github.com/xiaowine/Lyric-Getter/assets/122248140/d14cba88-0ab1-4432-a8d5-14f7f2b64aed)
![Screenshot_2023-12-13-11-40-50-843_cn lyric getter](https://github.com/xiaowine/Lyric-Getter/assets/122248140/216cd28b-b924-4aa6-b840-193a6b5dfbe0)

**Comment by xiaowine** [comment]
lsp没hook上，重新优化
